/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Authenticity__factory } from "./Authenticity__factory";
export { Upload__factory } from "./Upload__factory";
